services:
  coinflow-bot:
    build: .
    container_name: coinflow-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DATABASE_URL=sqlite:///data/coinflow.db
      - LOG_FILE=/app/logs/coinflow.log
      - OLLAMA_URL=http://host.docker.internal:11434
      - OLLAMA_MODEL=qwen3:8b
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    network_mode: bridge
