"""Localization system for CoinFlow bot."""

LOCALIZATION = {
    'en': {
        'welcome_new': '👋 *Welcome to CoinFlow Bot!*\n\nYour personal financial assistant for currency conversion, cryptocurrency analysis, and rate forecasting.\n\n🌍 Choose your language:',
        'welcome_back': '👋 *Welcome back!*\n\nI\'m ready to help you with currency conversions and cryptocurrency analysis.\n\n💡 Use the menu below to get started:',
        'language_set': '✅ Language set to English!',
        'main_menu': '📊 *Main Menu*\n\nChoose an action:',
        'quick_convert': '⚡ Quick Convert',
        'crypto_rates': '📈 Crypto Rates',
        'rate_charts': '📊 Rate Charts',
        'rate_prediction': '🔮 Rate Forecast',
        'compare_rates': '⚖️ Compare Rates',
        'calculator': '🧮 Calculator',
        'notifications': '🔔 Notifications',
        'favorites': '⭐ Favorites',
        'history': '📜 History',
        'settings': '⚙️ Settings',
        'about_btn': 'ℹ️ About',
        'stats_btn': '📊 Statistics',
        'back': '◀️ Back',
        'select_from_currency': '💰 *Select source currency:*\n\nChoose the currency you want to convert FROM:',
        'select_to_currency': '💵 *Select target currency:*\n\nChoose the currency you want to convert TO:',
        'enter_amount': '💵 Enter amount to convert:',
        'conversion_result': '💱 *Conversion Result*\n\n{amount} {from_curr} = *{result} {to_curr}*\n\n📊 Rate: 1 {from_curr} = {rate} {to_curr}\n⏰ Updated: {time}',
        'popular': '⭐ Popular',
        'fiat': '💵 Fiat',
        'crypto': '🪙 Crypto',
        'error': '❌ Error: {msg}',
        'rate_unavailable': 'Rate is currently unavailable. Please try again later.',
        'invalid_amount': 'Invalid amount. Please enter a valid number.',
        'comparing_rates': '⚖️ *Comparing rates for {symbol}*\n\nFetching data from exchanges...',
        'compare_result': '⚖️ *Price comparison for {symbol}/USDT:*\n\n{rates}\n\n📊 Average price: *${avg}*\n📈 Highest: ${high} ({high_ex})\n📉 Lowest: ${low} ({low_ex})\n📊 Spread: {spread}%',
        'chart_generating': '📊 Generating chart for {pair}...\n\nPlease wait...',
        'chart_ready': '📊 *Chart for {pair}*\n\n📈 Period: {period} days\n💰 Current price: ${current}\n📊 Average: ${avg}\n📈 High: ${high}\n📉 Low: ${low}',
        'prediction_generating': '🔮 Creating forecast for {pair}...\n\nThis may take up to a minute. Analyzing {days} days of data...',
        'prediction_ready': '🔮 *Forecast for {pair}*\n\n📊 Model: {model}\n📈 Trend: {trend}\n💰 Current: ${current}\n🎯 7-day forecast: ${forecast}\n\n⚠️ *DISCLAIMER:*\nThis is NOT financial advice. The forecast is based on mathematical models and does not account for market news or other factors.',
        'alert_set': '✅ *Alert set!*\n\n{pair}: {condition} ${target}\n\nI will notify you when the price reaches your target.',
        'alert_triggered': '🔔 *PRICE ALERT!*\n\n{pair} {condition} ${target}\n\nCurrent price: ${current}',
        'no_alerts': 'You have no active alerts.',
        'alerts_list': '🔔 *Your Alerts:*\n\n{alerts}',
        'calculator_mode': '🧮 *Calculator Mode*\n\nEnter an expression to calculate (e.g., `100 + 50 * 2`)\n\nOr use currency conversion: `100 USD to EUR`',
        'calc_result': '🧮 *Result:* {result}',
        'settings_menu': '⚙️ *Settings*',
        'favorites_empty': 'You have no favorite currencies yet.\n\nAdd favorites for quick access!',
        'favorites_list': '⭐ *Your Favorite Currencies:*\n\n{favorites}',
        'favorite_added': '⭐ {currency} added to favorites!',
        'favorite_removed': '❌ {currency} removed from favorites.',
        'history_empty': 'No conversion history yet.\n\nStart converting currencies!',
        'history_list': '📜 *Your Conversion History:*\n\n{history}',
        'select_currency_chart': '📊 *Select currency for chart:*\n\nChoose the cryptocurrency:',
        'select_currency_prediction': '🔮 *Select currency for AI forecast:*\n\nChoose the cryptocurrency:',
        'select_currency_compare': '⚖️ *Select currency to compare prices:*\n\nChoose the cryptocurrency:',
        'settings_updated': '✅ Settings updated successfully!',
        'language_changed': '🌍 Language changed to: {lang}',
        'about_text': 'ℹ️ *About CoinFlow Bot v2.0*\n\n🪙 CoinFlow is your ultimate financial assistant with advanced features:\n\n*New in v2.0:*\n• 💾 Persistent database\n• ⭐ Favorites system\n• 📜 Conversion history\n• ⚡ Smart caching\n• 📊 User statistics\n• 🔒 Enhanced security\n• 🚀 Better performance\n\n*Features:*\n• 💱 60+ currencies\n• 📊 5+ exchanges\n• 📈 Historical charts\n• 🔮 AI forecasting\n• 🔔 Price alerts\n• 🧮 Calculator\n\n📖 [GitHub](https://github.com/bobberdolle1/CoinFlow)\n\n⚠️ Not financial advice!',

        # Stocks
        'stocks': '📈 Stocks',
        'stocks_menu': '📈 *Stock Market*\n\nChoose a market:',
        'stocks_global': '🌍 Global Stocks',
        'stocks_russian': '🇷🇺 Russian Stocks & CBR',
        'stocks_global_select': '🌍 *Global Stocks*\n\nSelect a stock to view:',
        'stocks_russian_select': '🇷🇺 *Russian Stocks & CBR Rates*\n\nSelect a stock or currency:',
        'stock_error': '❌ Unable to fetch data for {ticker}. Please try again.',
        'cbr_error': '❌ Unable to fetch CBR rate for {currency}. Please try again.',
        'show_chart': '📊 Show Chart',
        'chart_sent': '✅ Chart sent above!',
        'loading': 'Loading',

        # CS2
        'cs2_skins': '🎮 CS2 Skins',
        'cs2_menu': '🎮 *CS2 Items Market*\n\nChoose a category:',
        'cs2_knives': 'Knives',
        'cs2_gloves': 'Gloves',
        'cs2_rifles': 'Rifles',
        'cs2_snipers': 'Snipers',
        'cs2_pistols': 'Pistols',
        'cs2_smgs': 'SMGs',
        'cs2_select_item': '🎮 *{category}*\n\nSelect an item:',
        'cs2_no_items': '❌ No items found in this category.',
        'cs2_fetching_prices': 'Fetching prices from marketplaces...',
        'cs2_price_error': '❌ Unable to fetch prices for this item. Please try again.',
        'refresh': 'Refresh',
        
        # Portfolio
        'portfolio': '💼 Portfolio',
        'portfolio_menu': '💼 *Your Portfolio*\n\nManage your investment portfolio:',
        'portfolio_empty': '📭 Your portfolio is empty.\n\nAdd assets to start tracking your investments!',
        'portfolio_add': '➕ Add Asset',
        'portfolio_view': '📊 View Portfolio',
        'portfolio_summary': '📈 Summary',
        'portfolio_export': '📤 Export',
        'portfolio_select_type': '📦 *Select Asset Type*\n\nWhat would you like to add?',
        'portfolio_type_crypto': '💰 Cryptocurrency',
        'portfolio_type_stock': '📈 Stock',
        'portfolio_type_fiat': '💵 Fiat Currency',
        'portfolio_type_cs2': '🎮 CS2 Item',
        'portfolio_enter_quantity': '📊 *Enter Quantity*\n\nHow many {asset} do you own?',
        'portfolio_added': '✅ Added {quantity} {asset} to your portfolio!',
        'portfolio_updated': '✅ Portfolio item updated successfully!',
        'portfolio_deleted': '✅ Portfolio item deleted.',
        'portfolio_error': '❌ Error: {error}',
        'portfolio_total_value': '💰 Total Value',
        'portfolio_profit_loss': '📊 Profit/Loss',
        'portfolio_distribution': '📊 Distribution by Type',
        'portfolio_item_details': '📊 *{name}*\n\n💼 Quantity: {quantity}\n💰 Current Price: ${price:.2f}\n💵 Total Value: ${value:.2f}',
        'portfolio_edit': '✏️ Edit',
        'portfolio_delete': '🗑️ Delete',
        'portfolio_confirm_delete': '⚠️ Are you sure you want to delete {asset}?',
        
        # Export
        'export': '📤 Export',
        'export_menu': '📤 *Export Data*\n\nChoose what to export:',
        'export_portfolio': '💼 Portfolio',
        'export_alerts': '🔔 Alerts',
        'export_history': '📜 History',
        'export_all': '📦 All Data (ZIP)',
        'export_generating': '⏳ Generating export file...',
        'export_ready': '✅ Export ready! Sending file...',
        'export_error': '❌ Export creation error: {error}',
        
        # News
        'news': '📰 News',
        'news_menu_title': 'Crypto News',
        'news_menu_desc': 'Stay updated with news about your favorite cryptocurrencies',
        'news_latest': '📄 Latest News',
        'news_subscriptions': '📊 My Subscriptions',
        'news_subscribe': '➕ Subscribe',
        'news_no_subscriptions': '💭 You have no news subscriptions.\n\nSubscribe to get notifications!',
        'news_none_found': '💭 No new news found',
        'news_sent': '✅ Sent {count} news items',
        'news_select_asset': '💰 **Select Cryptocurrency**\n\nWhich cryptocurrency would you like to receive news for?',
        'news_select_categories': 'Select news categories:',
        'news_subscription_created': '✅ Subscription to {asset} created!',
        'news_subscription_updated': '✅ Subscription to {asset} updated!',
        'your_subscriptions': 'Your Subscriptions',
        'active_subscriptions': 'Active subscriptions',
        'error_occurred': 'An error occurred',
        
        # Reports
        'reports': '📊 Reports',
        'reports_menu': '📊 **Analytics Reports**\n\nGenerate and schedule automated reports:',
        'report_generate': '📈 Generate Report',
        'report_weekly': '📅 Weekly Digest',
        'report_portfolio': '💼 Portfolio Report',
        'report_subscribe': '🔔 Subscribe to Reports',
        'report_generating': '⏳ Generating report...',
        'report_ready': '✅ Report generated!',
        'report_no_data': '📭 No data available for report',
        'report_subscription_created': '✅ Subscribed to {report_type} reports!',
        'report_subscription_updated': '✅ Report subscription updated!',

        # Theme
        'theme': '🎨 Theme',
        'theme_light': '☀️ Light',
        'theme_dark': '🌙 Dark',
        'theme_auto': '🔄 Auto',
        'theme_changed': '✅ Theme changed to: {theme}',
        'dashboard_btn': '🌐 Dashboard',
    },
    'ru': {
        'welcome_new': '👋 *Добро пожаловать в CoinFlow Bot!*\n\nВаш персональный финансовый ассистент для конвертации валют, анализа криптовалют и прогнозирования курсов.\n\n🌍 Выберите язык:',
        'welcome_back': '👋 *С возвращением!*\n\nЯ готов помочь вам с конвертацией валют и анализом криптовалют.\n\n💡 Используйте меню ниже для начала работы:',
        'language_set': '✅ Язык установлен: Русский!',
        'main_menu': '📊 *Главное меню*\n\nВыберите действие:',
        'quick_convert': '⚡ Быстрая конвертация',
        'crypto_rates': '📈 Курсы крипты',
        'rate_charts': '📊 Графики курсов',
        'rate_prediction': '🔮 Прогноз курса',
        'compare_rates': '⚖️ Сравнить курсы',
        'calculator': '🧮 Калькулятор',
        'notifications': '🔔 Уведомления',
        'favorites': '⭐ Избранное',
        'history': '📜 История',
        'settings': '⚙️ Настройки',
        'about_btn': 'ℹ️ О боте',
        'stats_btn': '📊 Статистика',
        'back': '◀️ Назад',
        'select_from_currency': '💰 *Выберите исходную валюту:*\n\nВыберите валюту, которую хотите конвертировать:',
        'select_to_currency': '💵 *Выберите целевую валюту:*\n\nВыберите валюту, в которую хотите конвертировать:',
        'enter_amount': '💵 Введите сумму для конвертации:',
        'conversion_result': '💱 *Результат конвертации*\n\n{amount} {from_curr} = *{result} {to_curr}*\n\n📊 Курс: 1 {from_curr} = {rate} {to_curr}\n⏰ Обновлено: {time}',
        'popular': '⭐ Популярные',
        'fiat': '💵 Фиат',
        'crypto': '🪙 Крипта',
        'error': '❌ Ошибка: {msg}',
        'rate_unavailable': 'Курс временно недоступен. Попробуйте позже.',
        'invalid_amount': 'Неверная сумма. Введите корректное число.',
        'comparing_rates': '⚖️ *Сравниваю курсы для {symbol}*\n\nПолучаю данные с бирж...',
        'compare_result': '⚖️ *Сравнение цен для {symbol}/USDT:*\n\n{rates}\n\n📊 Средняя цена: *${avg}*\n📈 Максимум: ${high} ({high_ex})\n📉 Минимум: ${low} ({low_ex})\n📊 Спред: {spread}%',
        'chart_generating': '📊 Создаю график для {pair}...\n\nПожалуйста, подождите...',
        'chart_ready': '📊 *График для {pair}*\n\n📈 Период: {period} дней\n💰 Текущая цена: ${current}\n📊 Среднее: ${avg}\n📈 Максимум: ${high}\n📉 Минимум: ${low}',
        'prediction_generating': '🔮 Создаю прогноз для {pair}...\n\nЭто может занять до минуты. Анализирую данные за {days} дней...',
        'prediction_ready': '🔮 *Прогноз для {pair}*\n\n📊 Модель: {model}\n📈 Тренд: {trend}\n💰 Текущая: ${current}\n🎯 Прогноз на 7 дней: ${forecast}\n\n⚠️ *ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ:*\nЭто НЕ финансовый совет. Прогноз основан на математических моделях и не учитывает рыночные новости и другие факторы.',
        'alert_set': '✅ *Уведомление установлено!*\n\n{pair}: {condition} ${target}\n\nЯ уведомлю вас, когда цена достигнет цели.',
        'alert_triggered': '🔔 *ЦЕНОВОЕ ОПОВЕЩЕНИЕ!*\n\n{pair} {condition} ${target}\n\nТекущая цена: ${current}',
        'no_alerts': 'У вас нет активных уведомлений.',
        'alerts_list': '🔔 *Ваши уведомления:*\n\n{alerts}',
        'calculator_mode': '🧮 *Режим калькулятора*\n\nВведите выражение для вычисления (например, `100 + 50 * 2`)\n\nИли используйте конвертацию валют: `100 USD to EUR`',
        'calc_result': '🧮 *Результат:* {result}',
        'settings_menu': '⚙️ *Настройки*',
        'favorites_empty': 'У вас пока нет избранных валют.\n\nДобавьте их для быстрого доступа!',
        'favorites_list': '⭐ *Ваши избранные валюты:*\n\n{favorites}',
        'favorite_added': '⭐ {currency} добавлена в избранное!',
        'favorite_removed': '❌ {currency} удалена из избранного.',
        'history_empty': 'История конвертаций пока пуста.\n\nНачните конвертировать валюты!',
        'history_list': '📜 *Ваша история конвертаций:*\n\n{history}',
        'select_currency_chart': '📊 *Выберите валюту для графика:*\n\nВыберите криптовалюту:',
        'select_currency_prediction': '🔮 *Выберите валюту для AI-прогноза:*\n\nВыберите криптовалюту:',
        'select_currency_compare': '⚖️ *Выберите валюту для сравнения цен:*\n\nВыберите криптовалюту:',
        'settings_updated': '✅ Настройки успешно обновлены!',
        'language_changed': '🌍 Язык изменён на: {lang}',
        'about_text': 'ℹ️ *О боте CoinFlow v2.0*\n\n🪙 CoinFlow — ваш финансовый ассистент с продвинутыми возможностями:\n\n*Новое в v2.0:*\n• 💾 Постоянная база данных\n• ⭐ Система избранного\n• 📜 История конвертаций\n• ⚡ Умное кэширование\n• 📊 Статистика пользователей\n• 🔒 Улучшенная безопасность\n• 🚀 Лучшая производительность\n\n*Возможности:*\n• 💱 60+ валют\n• 📊 5+ бирж\n• 📈 Исторические графики\n• 🔮 ИИ-прогнозирование\n• 🔔 Ценовые уведомления\n• 🧮 Калькулятор\n\n📖 [GitHub](https://github.com/bobberdolle1/CoinFlow)\n\n⚠️ Не является финансовым советом!',

        # Stocks
        'stocks': '📈 Акции',
        'stocks_menu': '📈 *Фондовый рынок*\n\nВыберите рынок:',
        'stocks_global': '🌍 Мировые акции',
        'stocks_russian': '🇷🇺 Российские акции и ЦБ',
        'stocks_global_select': '🌍 *Мировые акции*\n\nВыберите акцию для просмотра:',
        'stocks_russian_select': '🇷🇺 *Российские акции и курсы ЦБ РФ*\n\nВыберите акцию или валюту:',
        'stock_error': '❌ Не удалось получить данные для {ticker}. Попробуйте снова.',
        'cbr_error': '❌ Не удалось получить курс ЦБ для {currency}. Попробуйте снова.',
        'show_chart': '📊 Показать график',
        'chart_sent': '✅ График отправлен выше!',
        'loading': 'Загрузка',
        
        # CS2
        'cs2_skins': '🎮 CS2 Предметы',
        'cs2_menu': '🎮 *Рынок предметов CS2*\n\nВыберите категорию:',
        'cs2_knives': 'Ножи',
        'cs2_gloves': 'Перчатки',
        'cs2_rifles': 'Винтовки',
        'cs2_snipers': 'Снайперские',
        'cs2_pistols': 'Пистолеты',
        'cs2_smgs': 'ПП',
        'cs2_select_item': '🎮 *{category}*\n\nВыберите предмет:',
        'cs2_no_items': '❌ В этой категории не найдено предметов.',
        'cs2_fetching_prices': 'Получаю цены с площадок...',
        'cs2_price_error': '❌ Не удалось получить цены для этого предмета. Попробуйте снова.',
        'refresh': 'Обновить',
        
        # Portfolio
        'portfolio': '💼 Портфель',
        'portfolio_menu': '💼 *Ваш портфель*\n\nУправляйте инвестиционным портфелем:',
        'portfolio_empty': '📭 Ваш портфель пуст.\n\nДобавьте активы для отслеживания инвестиций!',
        'portfolio_add': '➕ Добавить актив',
        'portfolio_view': '📊 Показать портфель',
        'portfolio_summary': '📈 Сводка',
        'portfolio_export': '📤 Экспорт',
        'portfolio_select_type': '📦 *Выберите тип актива*\n\nЧто вы хотите добавить?',
        'portfolio_type_crypto': '💰 Криптовалюта',
        'portfolio_type_stock': '📈 Акция',
        'portfolio_type_fiat': '💵 Фиатная валюта',
        'portfolio_type_cs2': '🎮 Предмет CS2',
        'portfolio_enter_quantity': '📊 *Введите количество*\n\nСколько {asset} у вас есть?',
        'portfolio_added': '✅ Добавлено {quantity} {asset} в ваш портфель!',
        'portfolio_updated': '✅ Элемент портфеля успешно обновлён!',
        'portfolio_deleted': '✅ Элемент портфеля удалён.',
        'portfolio_error': '❌ Ошибка: {error}',
        'portfolio_total_value': '💰 Общая стоимость',
        'portfolio_profit_loss': '📊 Прибыль/Убыток',
        'portfolio_distribution': '📊 Распределение по типам',
        'portfolio_item_details': '📊 *{name}*\n\n💼 Количество: {quantity}\n💰 Текущая цена: ${price:.2f}\n💵 Общая стоимость: ${value:.2f}',
        'portfolio_edit': '✏️ Редактировать',
        'portfolio_delete': '🗑️ Удалить',
        'portfolio_confirm_delete': '⚠️ Вы уверены, что хотите удалить {asset}?',
        
        # Export
        'export': '📤 Экспорт',
        'export_menu': '📤 *Экспорт данных*\n\nВыберите, что экспортировать:',
        'export_portfolio': '💼 Портфель',
        'export_alerts': '🔔 Уведомления',
        'export_history': '📜 История',
        'export_all': '📦 Все данные (ZIP)',
        'export_generating': '⏳ Создаю файл экспорта...',
        'export_ready': '✅ Экспорт готов! Отправляю файл...',
        'export_error': '❌ Ошибка создания экспорта: {error}',
        
        # News
        'news': '📰 Новости',
        'news_menu_title': 'Криптоновости',
        'news_menu_desc': 'Отслеживайте новости по вашим любимым криптовалютам',
        'news_latest': '📄 Последние новости',
        'news_subscriptions': '📊 Мои подписки',
        'news_subscribe': '➕ Подписаться',
        'news_no_subscriptions': '💭 У вас нет подписок на новости.\n\nПодпишитесь, чтобы получать уведомления!',
        'news_none_found': '💭 Новых новостей не найдено',
        'news_sent': '✅ Отправлено {count} новостей',
        'news_select_asset': '💰 **Выберите криптовалюту**\n\nПо какой криптовалюте вы хотите получать новости?',
        'news_select_categories': 'Выберите категории новостей:',
        'news_subscription_created': '✅ Подписка на {asset} создана!',
        'news_subscription_updated': '✅ Подписка на {asset} обновлена!',
        'your_subscriptions': 'Ваши подписки',
        'active_subscriptions': 'Активных подписок',
        'error_occurred': 'Произошла ошибка',
        
        # Reports
        'reports': '📊 Отчеты',
        'reports_menu': '📊 **Аналитические отчеты**\n\nГенерируйте и настраивайте автоматические отчеты:',
        'report_generate': '📈 Создать отчет',
        'report_weekly': '📅 Еженедельный дайджест',
        'report_portfolio': '💼 Отчет по портфелю',
        'report_subscribe': '🔔 Подписаться на отчеты',
        'report_generating': '⏳ Создаю отчет...',
        'report_ready': '✅ Отчет готов!',
        'report_no_data': '📭 Нет данных для отчета',
        'report_subscription_created': '✅ Подписка на {report_type} отчеты создана!',
        'report_subscription_updated': '✅ Подписка на отчеты обновлена!',
        
        # Theme
        'theme': '🎨 Тема',
        'theme_light': '☀️ Светлая',
        'theme_dark': '🌙 Тёмная',
        'theme_auto': '🔄 Авто',
        'theme_changed': '✅ Тема изменена на: {theme}',
    }
}


def get_text(lang: str, key: str, **kwargs) -> str:
    """Get localized text."""
    return LOCALIZATION.get(lang, LOCALIZATION['en']).get(key, key).format(**kwargs)
