"""Localization system for CoinFlow bot."""

LOCALIZATION = {
    'en': {
        'welcome_new': '👋 *Welcome to CoinFlow Bot!*\n\nYour personal financial assistant for currency conversion, cryptocurrency analysis, and rate forecasting.\n\n🌍 Choose your language:',
        'welcome_back': '👋 *Welcome back!*\n\nI\'m ready to help you with currency conversions and cryptocurrency analysis.\n\n💡 Use the menu below to get started:',
        'language_set': '✅ Language set to English!',
        'main_menu': '📊 *Main Menu*\n\nChoose an action:',
        'quick_convert': '⚡ Quick Convert',
        'crypto_rates': '📈 Crypto Rates',
        'rate_charts': '📊 Rate Charts',
        'rate_prediction': '🔮 Rate Forecast',
        'compare_rates': '⚖️ Compare Rates',
        'calculator': '🧮 Calculator',
        'notifications': '🔔 Notifications',
        'favorites': '⭐ Favorites',
        'history': '📜 History',
        'settings': '⚙️ Settings',
        'about_btn': 'ℹ️ About',
        'stats_btn': '📊 Statistics',
        'back': '◀️ Back',
        'select_from_currency': '💰 *Select source currency:*\n\nChoose the currency you want to convert FROM:',
        'select_to_currency': '💵 *Select target currency:*\n\nChoose the currency you want to convert TO:',
        'enter_amount': '💵 Enter amount to convert:',
        'conversion_result': '💱 *Conversion Result*\n\n{amount} {from_curr} = *{result} {to_curr}*\n\n📊 Rate: 1 {from_curr} = {rate} {to_curr}\n⏰ Updated: {time}',
        'popular': '⭐ Popular',
        'fiat': '💵 Fiat',
        'crypto': '🪙 Crypto',
        'error': '❌ Error: {msg}',
        'rate_unavailable': 'Rate is currently unavailable. Please try again later.',
        'invalid_amount': 'Invalid amount. Please enter a valid number.',
        'comparing_rates': '⚖️ *Comparing rates for {symbol}*\n\nFetching data from exchanges...',
        'compare_result': '⚖️ *Price comparison for {symbol}/USDT:*\n\n{rates}\n\n📊 Average price: *${avg}*\n📈 Highest: ${high} ({high_ex})\n📉 Lowest: ${low} ({low_ex})\n📊 Spread: {spread}%',
        'chart_generating': '📊 Generating chart for {pair}...\n\nPlease wait...',
        'chart_ready': '📊 *Chart for {pair}*\n\n📈 Period: {period} days\n💰 Current price: ${current}\n📊 Average: ${avg}\n📈 High: ${high}\n📉 Low: ${low}',
        'prediction_generating': '🔮 Creating forecast for {pair}...\n\nThis may take up to a minute. Analyzing {days} days of data...',
        'prediction_ready': '🔮 *Forecast for {pair}*\n\n📊 Model: {model}\n📈 Trend: {trend}\n💰 Current: ${current}\n🎯 7-day forecast: ${forecast}\n\n⚠️ *DISCLAIMER:*\nThis is NOT financial advice. The forecast is based on mathematical models and does not account for market news or other factors.',
        'alert_set': '✅ *Alert set!*\n\n{pair}: {condition} ${target}\n\nI will notify you when the price reaches your target.',
        'alert_triggered': '🔔 *PRICE ALERT!*\n\n{pair} {condition} ${target}\n\nCurrent price: ${current}',
        'no_alerts': 'You have no active alerts.',
        'alerts_list': '🔔 *Your Alerts:*\n\n{alerts}',
        'calculator_mode': '🧮 *Calculator Mode*\n\nEnter an expression to calculate (e.g., `100 + 50 * 2`)\n\nOr use currency conversion: `100 USD to EUR`',
        'calc_result': '🧮 *Result:* {result}',
        'settings_menu': '⚙️ *Settings*',
        'favorites_empty': 'You have no favorite currencies yet.\n\nAdd favorites for quick access!',
        'favorites_list': '⭐ *Your Favorite Currencies:*\n\n{favorites}',
        'favorite_added': '⭐ {currency} added to favorites!',
        'favorite_removed': '❌ {currency} removed from favorites.',
        'history_empty': 'No conversion history yet.\n\nStart converting currencies!',
        'history_list': '📜 *Your Conversion History:*\n\n{history}',
        'about_text': 'ℹ️ *About CoinFlow Bot v2.0*\n\n🪙 CoinFlow is your ultimate financial assistant with advanced features:\n\n*New in v2.0:*\n• 💾 Persistent database\n• ⭐ Favorites system\n• 📜 Conversion history\n• ⚡ Smart caching\n• 📊 User statistics\n• 🔒 Enhanced security\n• 🚀 Better performance\n\n*Features:*\n• 💱 60+ currencies\n• 📊 5+ exchanges\n• 📈 Historical charts\n• 🔮 AI forecasting\n• 🔔 Price alerts\n• 🧮 Calculator\n\n📖 [GitHub](https://github.com/bobberdolle1/CoinFlow)\n\n⚠️ Not financial advice!',
    },
    'ru': {
        'welcome_new': '👋 *Добро пожаловать в CoinFlow Bot!*\n\nВаш персональный финансовый ассистент для конвертации валют, анализа криптовалют и прогнозирования курсов.\n\n🌍 Выберите язык:',
        'welcome_back': '👋 *С возвращением!*\n\nЯ готов помочь вам с конвертацией валют и анализом криптовалют.\n\n💡 Используйте меню ниже для начала работы:',
        'language_set': '✅ Язык установлен: Русский!',
        'main_menu': '📊 *Главное меню*\n\nВыберите действие:',
        'quick_convert': '⚡ Быстрая конвертация',
        'crypto_rates': '📈 Курсы крипты',
        'rate_charts': '📊 Графики курсов',
        'rate_prediction': '🔮 Прогноз курса',
        'compare_rates': '⚖️ Сравнить курсы',
        'calculator': '🧮 Калькулятор',
        'notifications': '🔔 Уведомления',
        'favorites': '⭐ Избранное',
        'history': '📜 История',
        'settings': '⚙️ Настройки',
        'about_btn': 'ℹ️ О боте',
        'stats_btn': '📊 Статистика',
        'back': '◀️ Назад',
        'select_from_currency': '💰 *Выберите исходную валюту:*\n\nВыберите валюту, которую хотите конвертировать:',
        'select_to_currency': '💵 *Выберите целевую валюту:*\n\nВыберите валюту, в которую хотите конвертировать:',
        'enter_amount': '💵 Введите сумму для конвертации:',
        'conversion_result': '💱 *Результат конвертации*\n\n{amount} {from_curr} = *{result} {to_curr}*\n\n📊 Курс: 1 {from_curr} = {rate} {to_curr}\n⏰ Обновлено: {time}',
        'popular': '⭐ Популярные',
        'fiat': '💵 Фиат',
        'crypto': '🪙 Крипта',
        'error': '❌ Ошибка: {msg}',
        'rate_unavailable': 'Курс временно недоступен. Попробуйте позже.',
        'invalid_amount': 'Неверная сумма. Введите корректное число.',
        'comparing_rates': '⚖️ *Сравниваю курсы для {symbol}*\n\nПолучаю данные с бирж...',
        'compare_result': '⚖️ *Сравнение цен для {symbol}/USDT:*\n\n{rates}\n\n📊 Средняя цена: *${avg}*\n📈 Максимум: ${high} ({high_ex})\n📉 Минимум: ${low} ({low_ex})\n📊 Спред: {spread}%',
        'chart_generating': '📊 Создаю график для {pair}...\n\nПожалуйста, подождите...',
        'chart_ready': '📊 *График для {pair}*\n\n📈 Период: {period} дней\n💰 Текущая цена: ${current}\n📊 Среднее: ${avg}\n📈 Максимум: ${high}\n📉 Минимум: ${low}',
        'prediction_generating': '🔮 Создаю прогноз для {pair}...\n\nЭто может занять до минуты. Анализирую данные за {days} дней...',
        'prediction_ready': '🔮 *Прогноз для {pair}*\n\n📊 Модель: {model}\n📈 Тренд: {trend}\n💰 Текущая: ${current}\n🎯 Прогноз на 7 дней: ${forecast}\n\n⚠️ *ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ:*\nЭто НЕ финансовый совет. Прогноз основан на математических моделях и не учитывает рыночные новости и другие факторы.',
        'alert_set': '✅ *Уведомление установлено!*\n\n{pair}: {condition} ${target}\n\nЯ уведомлю вас, когда цена достигнет цели.',
        'alert_triggered': '🔔 *ЦЕНОВОЕ ОПОВЕЩЕНИЕ!*\n\n{pair} {condition} ${target}\n\nТекущая цена: ${current}',
        'no_alerts': 'У вас нет активных уведомлений.',
        'alerts_list': '🔔 *Ваши уведомления:*\n\n{alerts}',
        'calculator_mode': '🧮 *Режим калькулятора*\n\nВведите выражение для вычисления (например, `100 + 50 * 2`)\n\nИли используйте конвертацию валют: `100 USD to EUR`',
        'calc_result': '🧮 *Результат:* {result}',
        'settings_menu': '⚙️ *Настройки*',
        'favorites_empty': 'У вас пока нет избранных валют.\n\nДобавьте их для быстрого доступа!',
        'favorites_list': '⭐ *Ваши избранные валюты:*\n\n{favorites}',
        'favorite_added': '⭐ {currency} добавлена в избранное!',
        'favorite_removed': '❌ {currency} удалена из избранного.',
        'history_empty': 'История конвертаций пока пуста.\n\nНачните конвертировать валюты!',
        'history_list': '📜 *Ваша история конвертаций:*\n\n{history}',
        'about_text': 'ℹ️ *О боте CoinFlow v2.0*\n\n🪙 CoinFlow — ваш финансовый ассистент с продвинутыми возможностями:\n\n*Новое в v2.0:*\n• 💾 Постоянная база данных\n• ⭐ Система избранного\n• 📜 История конвертаций\n• ⚡ Умное кэширование\n• 📊 Статистика пользователей\n• 🔒 Улучшенная безопасность\n• 🚀 Лучшая производительность\n\n*Возможности:*\n• 💱 60+ валют\n• 📊 5+ бирж\n• 📈 Исторические графики\n• 🔮 ИИ-прогнозирование\n• 🔔 Ценовые уведомления\n• 🧮 Калькулятор\n\n📖 [GitHub](https://github.com/bobberdolle1/CoinFlow)\n\n⚠️ Не является финансовым советом!',
    }
}


def get_text(lang: str, key: str, **kwargs) -> str:
    """Get localized text."""
    return LOCALIZATION.get(lang, LOCALIZATION['en']).get(key, key).format(**kwargs)
